language: node_js

cache:
  directories:
    - "Ëœ/.npm"

notifications:
  slack:
    rooms:
      - settlemint:5QuOPa3Z4kJbfbNIgei0asur#mint

node_js:
  - '9'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - npm i -g npm@latest
  - npm i -g truffle@4.1.6

install:
  - npm ci

script:
  - truffle test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release
  on:
    branch: master
    repo: DataBrokerDAO/erc20-bridge
